{	
  search(first: 25, type: ISSUE, query: "org:PUT_YOUR_ORG_HERE type:pr state:open created:>2017-09-01 sort:created-asc") {	
    nodes {	
      ... on PullRequest {	
        id	
        number	
        title	
        state	
        createdAt	
        commits(last: 1) {	
          nodes {	
            commit {	
              lastCommittedDate: committedDate	
            }	
          }	
        }	
        comments(last: 1) {	
          nodes {	
            lastCommentDate: createdAt	
          }	
        }	
      }	
    }	
    pageInfo {	
      endCursor	
    }	
  }	
}	
