name: codenotify
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  codenotify:
    runs-on: ubuntu-latest
    name: codenotify
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: sourcegraph/codenotify@v0.4
        id: codenotification
        env:
          # secrets.GITHUB_TOKEN is available by default, but it won't allow CODENOTIFY to mention GitHub teams.
          # If you want CODENOTIFY to be able to mention teams, then you need to create a personal access token
          # (https://github.com/settings/tokens) with scopes: repo, read:org.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
